# Generated by Django 3.2.5 on 2021-08-09 14:45

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.TextField(max_length=200, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image_preview', models.FileField(upload_to='news_img/', verbose_name='Изображение (preview)')),
                ('image', models.FileField(blank=True, upload_to='news_img/', verbose_name='Изображение для страницы новости')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='news_img/', verbose_name='Изображение (preview)')),
                ('image', models.ImageField(upload_to='news_img/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение для новости/статьи',
                'verbose_name_plural': 'Изображения для новости/статьи',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
