# Generated by Django 3.2.5 on 2021-08-09 15:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='announcement',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Анонс'),
        ),
    ]
