# Generated by Django 3.2.5 on 2021-08-09 14:01

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.FileField(upload_to='slide_main_img/', verbose_name='Изображение')),
                ('image_mobile', models.FileField(upload_to='slide_main_img/', verbose_name='Изображение для мобильной версии')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайд для главной страницы',
                'verbose_name_plural': 'Слайды для главной страницы',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.FileField(upload_to='social_link_img/', verbose_name='Изображение')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
