# Generated by Django 3.2.5 on 2021-08-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='link',
        ),
    ]
