# Generated by Django 3.2.5 on 2021-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210809_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
