# Generated by Django 3.2.5 on 2021-08-09 16:38

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('announcement', ckeditor.fields.RichTextField(blank=True, verbose_name='Анонс')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('image_preview', models.FileField(upload_to='workout_img/', verbose_name='Изображение (preview)')),
                ('image', models.FileField(blank=True, upload_to='workout_img/', verbose_name='Изображение для страницы тренировки')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
