# Generated by Django 3.2.5 on 2021-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
    ]
