# Generated by Django 2.2.24 on 2021-08-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_workout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='announcement',
            field=models.TextField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
