# Generated by Django 2.2.24 on 2021-08-19 15:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210809_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=200, verbose_name='Цвет css')),
            ],
            options={
                'verbose_name_plural': 'Расписание - направления занятий',
                'verbose_name': 'Расписание - направление занятия',
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Расписание - залы',
                'verbose_name': 'Расписание - зал',
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleInstructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Расписание - инструкторы',
                'verbose_name': 'Расписание - инструктор',
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.ScheduleDirections', verbose_name='Направление занятия')),
            ],
            options={
                'verbose_name_plural': 'Расписание - занятия',
                'verbose_name': 'Расписание - занятие',
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('date', models.DateField(verbose_name='Дата и время занятия')),
                ('time', models.CharField(max_length=200, verbose_name='Время занятия')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.ScheduleClasses', verbose_name='Занятие')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.ScheduleHall', verbose_name='Зал')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.ScheduleInstructors', verbose_name='Инструктор')),
            ],
            options={
                'verbose_name_plural': 'Расписание',
                'verbose_name': 'Расписание',
                'abstract': False,
                'ordering': ('order',),
            },
        ),
    ]
