# Generated by Django 2.2.24 on 2021-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_schedule_scheduleclasses_scheduledirections_schedulehall_scheduleinstructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledirections',
            name='color',
        ),
        migrations.AddField(
            model_name='schedulehall',
            name='color',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цвет css'),
        ),
    ]
