# Generated by Django 2.2.24 on 2021-08-19 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210819_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('title', models.CharField(max_length=200, verbose_name='Время')),
            ],
            options={
                'verbose_name_plural': 'Расписание - Время',
                'ordering': ('order',),
                'abstract': False,
                'verbose_name': 'Время',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
    ]
