# Generated by Django 2.2.24 on 2021-08-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20210819_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletime',
            options={'ordering': ('order',), 'verbose_name': 'Расписание - время', 'verbose_name_plural': 'Расписание - время'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.ScheduleTime', verbose_name='Время занятия'),
        ),
    ]
