# Generated by Django 2.2.24 on 2021-08-27 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210819_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestViewFrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь формы "Оставить заявку"',
                'verbose_name_plural': 'Пользователи формы "Оставить заявку (стать тренером)"',
            },
        ),
    ]
