# Generated by Django 3.2.5 on 2021-07-15 15:43

import adminsortable.fields
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('value', ckeditor.fields.RichTextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'HTML Блок',
                'verbose_name_plural': 'HTML Блоки',
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('value', models.ImageField(upload_to='block/images/', verbose_name='Изображение')),
                ('width', models.CharField(blank=True, max_length=200, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, max_length=200, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Image Блок',
                'verbose_name_plural': 'Image Блоки',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тэг title')),
                ('description', models.TextField(verbose_name='Тэг description')),
                ('keywords', models.TextField(verbose_name='Тэг keywords')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='Относительный URL')),
            ],
            options={
                'verbose_name': 'Метатэг',
                'verbose_name_plural': 'Метатэги',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicated', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Тело')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Слайдер изображений',
                'verbose_name_plural': 'Слайдеры изображений',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='StringBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'String Блок',
                'verbose_name_plural': 'String Блоки',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Text Блок',
                'verbose_name_plural': 'Text Блоки',
            },
        ),
        migrations.CreateModel(
            name='SliderBlockSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_block/images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Вес')),
                ('block', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itm_main.sliderblock', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('order',),
            },
        ),
    ]
