"""
Django settings for itm_evolution_2021 project.

Generated by 'django-admin startproject' using Django 2.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yb6w8^d0smg(%s*d)4$ppr8as0&d8d7j(l#sn&!_4z9g)925sd'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['old.fitnessevo.beget.tech', 'fitnessevo.beget.tech', 'evolution-fitness.ru']


# Application definition

INSTALLED_APPS = [
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'adminsortable',
    'itm_common',
    'itm_main',
    'main',
    'news',
    'stock',
    'team',
    'easy_thumbnails',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itm_evolution_2021.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                    os.path.join(BASE_DIR, 'templates'),
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itm_evolution_2021.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fitnessevo_fold',
        'USER': 'fitnessevo_fold',
        'PASSWORD': 'Wsx951753',
        'HOST': 'localhost',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT='static'
STATIC_ROOT = '/home/f/fitnessevo/old.evolution-fitness-sales.ru/public_html/static/'

MEDIA_URL = '/media/'
#MEDIA_ROOT = 'media'
MEDIA_ROOT = '/home/f/fitnessevo/old.evolution-fitness-sales.ru/public_html/media/'

ITM_SITE_NAME = 'Фитнес-клуб «Эволюция»'

DEFAULT_PAGINATION_COUNT = 9

DEFAULT_PAGES_TEMPLATE = 'main/page_detail.html'

EMAIL_HOST = 'smtp.yandex.ru'

EMAIL_PORT = 465

EMAIL_USE_SSL = True

EMAIL_HOST_USER = 'no-reply@site-itm.ru'

EMAIL_HOST_USER_CONTACTS_FORM = [ 'info@evolution-fitness.ru', 'savilova-ekaterina@mail.ru', ]

EMAIL_HOST_PASSWORD = 'GieQu4he'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER_CONTACTS_FORM

FILEBROWSER_DIRECTORY = ""

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
     'toolbar': 'None'
    },
}

FILE_UPLOAD_PERMISSIONS = 0o644
